version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/my-node-app

hooks:
  BeforeInstall:
    - location: scripts/stop_server.sh
      timeout: 120
      runas: ubuntu

  AfterInstall:
    - location: scripts/prepare.sh
      timeout: 120
      runas: ubuntu
    - location: scripts/install_dependencies.sh
      timeout: 900
      runas: ubuntu

  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 180
      runas: ubuntu
      

  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 120
      runas: ubuntu
